package cs155.jray;

/**
 * This represents a material (either inside or outside on an object) it
 * contains Color3D values for the emissive, ambient, diffuse, and specular
 * reflection properties of the material as well as a hardness coefficient for
 * the specular reflection. In addition, it specifies how much of the light
 * coming from that point is generated by the reflection ray, and how much from
 * the refraction ray (both values between 0 and 1 summing to less than 1), the
 * remainder comes from the material itself. Finally, it specifies the material
 * texture and the extent to which the texture is averaged with the other
 * material colors.
 **/

public class Material {
	public static Material defaultMat = new Material();

	public Color3D emissive = Color3D.BLACK, ambient = Color3D.BLACK,
			diffuse = Color3D.WHITE.scale(0.5d), specular = Color3D.WHITE;
	public int hardness = 25;
	public double reflect = 0.05, refract = 0.0;
	public double texWeight = 0.0; // ratio of texture to material color
	public double IOR = 1.0;
	public Texture texture = Texture.WHITE;

	public Material() {
		;
	}

	public Material(Color3D emissive, Color3D ambient, Color3D diffuse,
			Color3D specular, int hardness) {
		this.emissive = emissive;
		this.ambient = ambient;
		this.diffuse = diffuse;
		this.specular = specular;
		this.hardness = hardness;

	}
}
